### PR TITLE
Deprecate more cruft before 2.0

### PR DESCRIPTION
**Pull request by kkoopa**
`NanGetPointerSafe` and `NanSetPointerSafe` were only used in deprecated string conversion routines. Probably has no external users.

The OptionValue routines are just sugar with a narrow (?) use case.

/cc @rvagg: Objections?

### CODE REVIEW

**Comment by rvagg** [comment]
no objections, I've only used them in the various leveldown* packages and put them in here in the assumption that they'd be more generally useful but they turn out to be a bit too specific to the pattern I was using and would be fine to see them removed (actually, we'll what kind of a fuss we create by deprecating them, that'll be interesting)

**Comment by gigadude** [comment]
I'd just started using them... maybe move them into a nanutil.h (and round out the set of C++ types while you're at it)?

**Comment by ralphtheninja** [comment]
Would it be possible to release other c-modules as well and use them just like nan?

**Comment by ralphtheninja** [comment]
@kkoopa When will 2.0 be released you think?

**Comment by kkoopa** [comment]
After the new `Buffer` implementation is done in io.js.

**Pull request merged**
