### PR TITLE
Nomacro

### PR DESCRIPTION
**Pull request by kkoopa**
Replaced a bunch of macros with classes. The only ones left are `NanReturnValue` et al. Can't figure out a good way of removing them. I considered wrapping all exported functions similarly to the weak callback and adding a `NanExport` function, but that leaves the problem of resolving the right function when doing new `FunctionTemplate` or `Function`.

### CODE REVIEW

**Comment by kkoopa** [comment]
I've come up with a plan that might work.

**Comment by rvagg** [comment]
The only thing I'm concerned about here is having different addons compile against different versions of NAN, we're running a greater risk of ABI incompatibilities when moving away from macro's aren't we? Are we going to end up needing a `NAN_MODULE_VERSION` or of our own to do some checking and erroring at load time?

**Comment by kkoopa** [comment]
NAN is a header only library, so ABI changes would not be a problem.

**Comment by kkoopa** [comment]
Merged as e931e216c4e59ffddc462e1d4f11f247e53a83b2.

**Pull request closed without merging**
