### PR TITLE
Added io.js WG governance section

### PR DESCRIPTION
**Pull request by rvagg**
Proposing a governance structure compatible with the io.js project, in preparation for a move to the _iojs_ GitHub org.

Note that this is based on the bootstrap governance structure with the following broad changes:

 * No distinction between WG members and "Collaborators", there is only one level of hierarchy here as there has always been
 * No requirement for meetings, everything can be done via GitHub as it always has been done
 * No conduct section

Collaborators please review and please comment on whether you'd like to transfer to the io.js Working Group.

Obvious members of the NAN WG:
* @rvagg
* @kkoopa
* @brett19
* @bnoordhuis
* @agnat

@trevnorris and @TooTallNate, I'm unsure of whether you're still interested in participating in this project. I'd love you both to continue to be involved but would rather give you the opportunity to bail now if you don't think you can find the time or interest to participate on a regular basis. Please let us know your thoughts.

### CODE REVIEW

**Comment by rvagg** [comment]
See also https://github.com/iojs/io.js/pull/1226

Plus, I'm also proposing to move  [node-addon-examples](https://github.com/rvagg/node-addon-examples) (to be renamed "addon-examples") to the _iojs_ org to be managed by this WG, feel free to disagree with that though.

**Comment by hgupta9** [comment]
@rvagg, can you add this in?

https://github.com/rvagg/nan/pull/297

**Comment by rvagg** [comment]
no, this is a separate discussion sorry

**Comment by rvagg** [comment]
Changed the name of the WG to "Addon API Working Group", open to suggestions on better names though

**Comment by rvagg** [comment]
merged

**Pull request merged**
